gui/src/servericonwidget.cpp: add missing import of QPainterPath
Otherwise building fails with the following error:

error: aggregate ‘QPainterPath path’ has incomplete type and cannot be
defined

Closes #253

Signed-off-by: Mateusz Gozdek <mgozdekof@gmail.com>